version: "3.9"

services:
#  mongo:
#    image: mongo
#    restart: always
#    ports:
#      - "27017:27017"
#    volumes:
#      - ./data/mongo:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=root
#      - MONGO_INITDB_ROOT_PASSWORD=Quandz@@2083
#    networks:
#      - fasfood_network

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=Quandz@@2083
    networks:
      - fasfood_network

  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server --requirepass Quandz@@2083
    volumes:
      - ./data/redis:/data
    ports:
      - "6379:6379"
    networks:
      - fasfood_network

  discovery-service:
    image: discovery-service:latest
    build:
      context: ./DiscoveryService
    restart: always
    ports:
      - "8761:8761"
    networks:
      - fasfood_network

  gateway:
    image: gateway:latest
    build:
      context: ./ApiGateway
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./logs/gateway:/app/logs
    environment:
    - EUREKA_URLS=http://discovery-service:8761/eureka/
    networks:
      - fasfood_network

  iam:
    image: iam:latest
    build:
      context: ./IamService
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - ./logs/iam:/app/logs
    environment:
      - EUREKA_URLS=http://discovery-service:8761/eureka/
      - REDIS_HOST=redis
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/FasFood?currentSchema=iam&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JWK_SSO_URL=http://keycloak:8080/realms/FasFood/protocol/openid-connect/certs
      - JWK_INTERNAL_URL=http://iam:8081/api/certificate/.well-known/jwks.json
      - KEYCLOAK_URL=http://keycloak:8080/realms/FasFood
      - RETURN_URL=https://www.futabus.online
      - GOOGLE_REDIRECT_URL=https://www.futabus.online
    networks:
      - fasfood_network

  storage:
    image: storage:latest
    build:
      context: ./StorageService
    restart: always
    ports:
      - "8082:8082"
    volumes:
      - ./data/uploads:/app/data/uploads
      - ./logs/storage:/app/logs
    environment:
      - EUREKA_URLS=http://discovery-service:8761/eureka/
      - REDIS_HOST=redis
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/FasFood?currentSchema=storage&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JWK_SSO_URL=http://keycloak:8080/realms/FasFood/protocol/openid-connect/certs
      - JWK_INTERNAL_URL=http://iam:8081/api/certificate/.well-known/jwks.json
      - KEYCLOAK_URL=http://keycloak:8888/realms/FasFood
      - KEYCLOAK_URL=http://keycloak:8080/realms/FasFood
    networks:
      - fasfood_network

  notification:
    image: notification:latest
    build:
      context: ./NotificationService
    restart: always
    ports:
      - "8083:8083"
    volumes:
      - ./logs/notification:/app/logs
    environment:
      - EUREKA_URLS=http://discovery-service:8761/eureka/
      - REDIS_HOST=redis
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/FasFood?currentSchema=notification&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JWK_SSO_URL=http://keycloak:8080/realms/FasFood/protocol/openid-connect/certs
      - JWK_INTERNAL_URL=http://iam:8081/api/certificate/.well-known/jwks.json
      - KEYCLOAK_URL=http://keycloak:8888/realms/FasFood
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094
      - KEYCLOAK_URL=http://keycloak:8080/realms/FasFood
    networks:
      - fasfood_network

  trip:
    image: trip:latest
    build:
      context: ./TripService
    restart: always
    ports:
      - "8084:8084"
    volumes:
      - ./logs/trip:/app/logs
    environment:
      - EUREKA_URLS=http://discovery-service:8761/eureka/
      - REDIS_HOST=redis
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/FasFood?currentSchema=trip&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JWK_SSO_URL=http://keycloak:8080/realms/FasFood/protocol/openid-connect/certs
      - JWK_INTERNAL_URL=http://iam:8081/api/certificate/.well-known/jwks.json
      - KEYCLOAK_URL=http://keycloak:8080/realms/FasFood
    networks:
      - fasfood_network

  booking:
    image: booking:latest
    build:
      context: ./BookingService
    restart: always
    ports:
      - "8085:8085"
    volumes:
      - ./logs/booking:/app/logs
    environment:
      - EUREKA_URLS=http://discovery-service:8761/eureka/
      - REDIS_HOST=redis
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/FasFood?currentSchema=booking&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JWK_SSO_URL=http://keycloak:8080/realms/FasFood/protocol/openid-connect/certs
      - JWK_INTERNAL_URL=http://iam:8081/api/certificate/.well-known/jwks.json
      - KEYCLOAK_URL=http://keycloak:8080/realms/FasFood
      - BOOTSTRAP_SERVERS=kafka1:9092,kafka2:9093,kafka3:9094
      - RETURN_URL=https://www.futabus.online
    networks:
      - fasfood_network

  payment:
    image: payment:latest
    build:
      context: ./PaymentService
    restart: always
    ports:
      - "8086:8086"
    volumes:
      - ./logs/payment:/app/logs
    environment:
      - EUREKA_URLS=http://discovery-service:8761/eureka/
      - REDIS_HOST=redis
      - POSTGRES_URL=jdbc:postgresql://postgres:5432/FasFood?currentSchema=payment&useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JWK_SSO_URL=http://keycloak:8080/realms/FasFood/protocol/openid-connect/certs
      - JWK_INTERNAL_URL=http://iam:8081/api/certificate/.well-known/jwks.json
      - KEYCLOAK_URL=http://keycloak:8080/realms/FasFood
      - RETURN_URL=https://www.futabus.online
    networks:
      - fasfood_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: >
      start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak
      - KC_DB_USERNAME=iam
      - KC_DB_PASSWORD=iam123@
    ports:
      - "8888:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - fasfood_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fasfood_network

  kafka1:
    image: confluentinc/cp-kafka:latest
    container_name: kafka1
    restart: unless-stopped
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_MESSAGE_MAX_BYTES: 10485760
      KAFKA_REPLICA_FETCH_MAX_BYTES: 10485760
      KAFKA_HEAP_OPTS: "-Xmx4G -Xms4G"
    networks:
      - fasfood_network
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:latest
    container_name: kafka2
    restart: unless-stopped
    ports:
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093,PLAINTEXT_HOST://localhost:29093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_HEAP_OPTS: "-Xmx4G -Xms4G"
    networks:
      - fasfood_network
    depends_on:
      - zookeeper

  kafka3:
    image: confluentinc/cp-kafka:latest
    container_name: kafka3
    restart: unless-stopped
    ports:
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094,PLAINTEXT_HOST://localhost:29094
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094,PLAINTEXT_HOST://0.0.0.0:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_NUM_PARTITIONS: 10
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_HEAP_OPTS: "-Xmx4G -Xms4G"
    networks:
      - fasfood_network
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    ports:
      - "1111:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - fasfood_network
    depends_on:
      - kafka1
      - kafka2
      - kafka3

networks:
  fasfood_network:
    driver: bridge