server:
  port: ${PORT:8080}
  servlet:
    context-path: ${SERVICE_PATH:/}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URLS:http://localhost:8761/eureka/}

springdoc:
  webjars:
    prefix:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        displayName: API Gateway Service
      - url: iam/v3/api-docs
        name: IAM Service
        displayName: IAM Service
      - url: storage/v3/api-docs
        name: Storage Service
        displayName: Storage Service
      - url: trip/v3/api-docs
        name: Trip Service
        displayName: Trip Service
      - url: booking/v3/api-docs
        name: Booking Service
        displayName: Booking Service
      - url: notification/v3/api-docs
        name: Notification Service
        displayName: Notification Service
      - url: payment/v3/api-docs
        name: Payment Service
        displayName: Payment Service

spring:
  application:
    name: gateway
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
      WRITE_DATE_TIMESTAMPS_AS_NANOSECONDS: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          '[/**]':
#            allowedOrigins:
#              - "http://localhost:3000"
#              - "http://127.0.0.1:5500"
#              - "https://yourfrontend.com"
#              - "https://futabus.netlify.app"
#              - "https://www.futabus.online"
#              - "https://www.admin.futabus.online"
            allowed-origin-patterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true
      default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      routes:
         - id: iam
           uri: lb://iam
           predicates:
              - Path=/iam/**
           filters:
            - StripPrefix=1
         - id: storage
           uri: lb://storage
           predicates:
             - Path=/storage/**
           filters:
             - StripPrefix=1
         - id: trip
           uri: lb://trip
           predicates:
             - Path=/trip/**
           filters:
             - StripPrefix=1
         - id: booking
           uri: lb://booking
           predicates:
             - Path=/booking/**
           filters:
             - StripPrefix=1
         - id: notification
           uri: lb://notification
           predicates:
             - Path=/notification/**
           filters:
             - StripPrefix=1
         - id: payment
           uri: lb://payment
           predicates:
             - Path=/payment/**
           filters:
             - StripPrefix=1
         - id: keycloak
           uri: http://keycloak:8080
           predicates:
             - Path=/keycloak/**
           filters:
             - StripPrefix=1

